### ISSUE TITLE
[REQUEST] Not working with some mob from other Mod! Maybe a Config file to add them?

### ISSUE THREAD

**Issue by Discrae** [Raverbury/AggroIndicator#4]
Hey, it seems that with "Creeper Overhaul" and "Enderman Overhaul" the Aggro Indicator do not appear!
![no indcator](https://github.com/Raverbury/AggroIndicator/assets/125488609/6f0414ec-53cc-4d52-8e3a-9a1ceb0d429b)

Edit: "Naturalist" Mod too !
Maybe can you add a config file too let us adding mob from other mod?

**Comment by Raverbury** [comment]
Sorry for replying late, I'll try to look into it this weekend or next week. Which version of the mod were you using?

**Comment by Raverbury** [comment]
Fixed with 9bab8975379f7228632b6b3c09bd1ba997403ef7
