### ISSUE TITLE
Friends&Foes crash

### ISSUE THREAD

**Issue by Faboslav** [Raverbury/AggroIndicator#6]
Hello i got this issue report here: https://github.com/Faboslav/friends-and-foes/issues/260, seems to be something badly handled on your side of the mod based on the logs

**Comment by Raverbury** [comment]
The crash is from using an old event method name from neoforge beta. I have changed it to what is being used in neoforge 21.0.167 and bumped neoforge dependency up as well with c691d883cea1f0ad79b95072730c4652a4da2559. That should hopefully fix it.
